name: Build Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_REGISTRY_AUTH: ${{secrets.DOCKER_REGISTRY_AUTH}}
          DOCKER_REGISTRY_TOKEN: ${{secrets.DOCKER_REGISTRY_TOKEN}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Image
        run: docker build. --file Dockerfile --tag cloudflared:$(date + %s)
      - name: Push
        run: docker push ${{secrets.DOCKER_REGISTRY_AUTH}}/cloudflared
