name: Build Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_AUTH }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Fetch cloudflared Binary
      - run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/runner.sh"

          # run script
          "${GITHUB_WORKSPACE}/.github/runner.sh download_argo"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_AUTH }}/cloudflared:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
